// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC5qAWY0ybxskD-QJu67Qg0flUQ9OhwwQ',
    appId: '1:225152013158:web:22de6eedc0c93c30cdeea7',
    messagingSenderId: '225152013158',
    projectId: 'smart-parking-1d875',
    authDomain: 'smart-parking-1d875.firebaseapp.com',
    storageBucket: 'smart-parking-1d875.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_OIgy9C92maBwz-qqVqllCiO4qbzLhQ',
    appId: '1:225152013158:android:fb5e073606a114f5cdeea7',
    messagingSenderId: '225152013158',
    projectId: 'smart-parking-1d875',
    storageBucket: 'smart-parking-1d875.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXuO5jUzfOtzqQoKx5bG3avaUBrYs3Pw',
    appId: '1:225152013158:ios:ef9fd62ac055b063cdeea7',
    messagingSenderId: '225152013158',
    projectId: 'smart-parking-1d875',
    storageBucket: 'smart-parking-1d875.firebasestorage.app',
    iosClientId: '225152013158-18p4h9p0890h8bcur2v7lleo1hc0jrsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeXuO5jUzfOtzqQoKx5bG3avaUBrYs3Pw',
    appId: '1:225152013158:ios:ef9fd62ac055b063cdeea7',
    messagingSenderId: '225152013158',
    projectId: 'smart-parking-1d875',
    storageBucket: 'smart-parking-1d875.firebasestorage.app',
    iosClientId: '225152013158-18p4h9p0890h8bcur2v7lleo1hc0jrsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC5qAWY0ybxskD-QJu67Qg0flUQ9OhwwQ',
    appId: '1:225152013158:web:d3b6b30c3f3b4ab5cdeea7',
    messagingSenderId: '225152013158',
    projectId: 'smart-parking-1d875',
    authDomain: 'smart-parking-1d875.firebaseapp.com',
    storageBucket: 'smart-parking-1d875.firebasestorage.app',
  );
}
